- name: "Include OS-specific tasks"
  include: "os/{{ ansible_distribution }}/main.yml"

- name: Install discovery monitoring
  template:
    src: "etc/telegraf/telegraf.d/noc-discovery.conf.j2"
    dest: "{{ telegraf_confd_path }}/noc-discovery.conf"
  notify: reload telegraf
  tags:
    - config
    - telegraf


- name: Tune sysctl.conf for keepalive
  sysctl:
    name: "{{item.name}}"
    value: "{{item.value}}"
    state: present
    reload: yes
  with_items:
    - { name: 'net.ipv4.tcp_keepalive_time', value: 60 }
    - { name: 'net.ipv4.tcp_keepalive_intvl', value: 10 }
    - { name: 'net.ipv4.tcp_keepalive_probes', value: 3 }
  tags:
    - config
  when: "'Linux' in ansible_system"