---
- name: include nsqadmin os specific tasks
  include: "os/{{ ansible_distribution }}/main.yml"

- name: Install nsqadmin monitoring
  template:
    src: "etc/telegraf/telegraf.d/nsqadmin.conf.j2"
    dest: "{{etc_prefix}}/telegraf/telegraf.d/nsqadmin.conf"
  notify: reload telegraf
  tags:
    - config
    - telegraf

- name: install nsqadmin config
  template:
    src: etc/config/nsqadmin.conf.j2
    dest: "{{noc_root}}/var/etc/nsq/nsqadmin.conf"
  notify: restart nsqadmin
  tags:
    - config

- name: Enable nsqadmin system service
  service:
    name: "nsqadmin"
    enabled: yes
    state: started