- name: "Include OS-specific tasks"
  include: "os/{{ ansible_distribution }}/main.yml"

- name: Install syslogcollector monitoring
  template:
    src: "etc/telegraf/telegraf.d/noc-syslogcollector.conf.j2"
    dest: "{{etc_prefix}}/telegraf/telegraf.d/noc-syslogcollector.conf"
  notify: reload telegraf
  when: noc_cfg1.changed or noc_cfg2.changed or noc_cfg3.changed or noc_cfg4.changed
  tags:
    - config
    - telegraf
