- name: "Include OS-specific tasks"
  include: "os/{{ ansible_distribution }}/main.yml"

- name: Install memcached monitoring
  template:
    src: "etc/telegraf/telegraf.d/memcached.conf.j2"
    dest: "{{etc_prefix}}/telegraf/telegraf.d/memcached.conf"
  notify: reload telegraf
  tags:
    - config
    - telegraf


- name: Install memcached config
  template:
    src: "etc/{{ ansible_distribution }}/memcached.conf.j2"
    dest: "{{ memcahed_conf }}"
  notify: reload memcached
  tags:
    - config

