- name: "Include OS-specific tasks"
  include: "os/{{ ansible_distribution }}/main.yml"

- name: Install pgbouncer monitoring
  template:
    src: "etc/telegraf/telegraf.d/pgbouncer.conf.j2"
    dest: "{{etc_prefix}}/telegraf/telegraf.d/pgbouncer.conf"
  notify: reload telegraf
  tags:
    - config
    - telegraf

- name: Install pgbouncer config
  template:
    src: "etc/pgbouncer/pgbouncer.ini.j2"
    dest: "{{etc_prefix}}/pgbouncer/pgbouncer.ini"
  notify: reload pgbouncer
  register: pgbouncer_configured
  tags:
    - config

- name: restart pgbouncer
  service:
    name: pgbouncer
    enabled: yes
    state: restarted
  when: "pgbouncer_configured.changed==True"

- name: start pgbouncer
  service:
    name: pgbouncer
    enabled: yes
    state: reloaded