---
- name: Install Ubuntu system packages
  become: "True"
  apt:
    name: "{{ packages }}"
    update_cache: "True"
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  vars:
    packages:
      - ca-certificates
      - unzip
      - sudo
      - curl
      - apt-transport-https
      - dbus  # to setup hostname
      - build-essential  # ub18 hasn't it usually
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements
