---
- name: Add RedHat Nginx repo
  yum:
    name: http://nginx.org/packages/rhel/{{ ansible_distribution_major_version }}/noarch/RPMS/nginx-release-rhel-{{ ansible_distribution_major_version }}-0.el{{ ansible_distribution_major_version }}.ngx.noarch.rpm
    state: present
  environment:
    http_proxy: "{{http_proxy}}"
  tags:
    - repo

- name: Install service monitoring
  template:
    src: "{{item}}"
    dest: "/{{item[:-3]}}"
    force: no
  with_items:
    - "etc/telegraf/telegraf.d/discovery.conf.j2"
    - "etc/telegraf/telegraf.d/fm-monitor.conf.j2"
  notify: reload telegraf
  tags:
    - config

- name: Install Nginx
  yum:
    name: nginx
    state: latest
    disable_gpg_check: yes
  environment:
    http_proxy: "{{http_proxy}}"

- name: Remove default.conf site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: restart nginx

- name: Enable Nginx system service
  service:
    name: "{{ nginx_system_service }}"
    enabled: yes
    state: started
