version: "2"
services:
  shell:
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    working_dir: /docs
    volumes:
      - .:/docs

  html-en:
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    volumes:
      - .:/docs
    working_dir: /docs
    command: sphinx-build -a -E -b html src/en build/en

  html-en-inc:
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    volumes:
      - .:/docs
    working_dir: /docs
    command: sphinx-build -b html src/en build/en

  html:
    depends_on:
      - html-en
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    volumes:
      - .:/docs
    working_dir: /docs
    command: /bin/true

  epub-en:
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    volumes:
      - .:/docs
    working_dir: /docs
    command: sphinx-build -b epub src/en build/epub/en

  epub:
    depends_on:
      - epub-en
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    volumes:
      - .:/docs
    working_dir: /docs
    command: /bin/true

  build:
    depends_on:
      - html
      - epub
    image: "registry.getnoc.com/infrastructure/docs:master"
    restart: "no"
    volumes:
      - .:/docs
    working_dir: /docs
    command: /bin/true

  serve:
    image: "nginx:mainline"
    restart: "no"
    volumes:
      - ./build/:/usr/share/nginx/html
    ports:
      - 48888:80
