---
- name: Get CH Key from remote server
  get_url:
   url: "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x{{ ch_apt_key_id }}"
   dest: "/tmp/ch_apt_key.gpg"
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - repo

- name: Add CH apt key
  apt_key:
    id: "{{ ch_apt_key_id }}"
    file: "/tmp/ch_apt_key.gpg"
    state: present
  tags:
    - repo

- name: Install CH
  apt:
    name: "{{ packages }}"
    state: present
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  vars:
    packages:
      - clickhouse-client={{ clickhouse_version }}
      - clickhouse-server={{ clickhouse_version }}
      - clickhouse-common-static={{ clickhouse_version }}
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements
