---
- name: remove obsolete grafana repo
  file:
    path: packagecloud_io_grafana_stable_debian.list
    state: absent
  tags:
    - repo

- name: Get Grafana Key from remote server
  get_url:
   url: "https://packages.grafana.com/gpg.key"
   dest: "/tmp/grafana_apt_key.gpg"
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - repo

- name: Add Grafana apt key
  apt_key:
    file: "/tmp/grafana_apt_key.gpg"
    state: present
  tags:
    - repo

- name: Add Grafana repo
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    update_cache: "True"
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - repo

- name: Install Ubuntu packages
  apt:
    name: grafana={{ grafana_version }}
    state: present
    update_cache: "True"
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  notify: restart grafana
  tags:
    - requirements
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
