---
- name: Set mongod-arbiter defaults
  template: src="CentOS/etc/sysconfig/mongod-arbiter.j2" dest="/etc/sysconfig/mongod-arbiter"
  notify: restart mongod-arbiter

- name: Check mongod-arbiter init file
  stat: path=/etc/init.d/mongod-arbiter
  register: s

- name: Create mongod-arbiter init file
  shell: "sed -e 's/sysconfig\\/mongod/sysconfig\\/mongod-arbiter/' < /etc/init.d/mongod > /etc/init.d/mongod-arbiter && chmod a+x /etc/init.d/mongod-arbiter"
  when: s.stat.isfile is not defined
