---
- name: Install memcached
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  with_items:
    - memcached
    - netcat
  environment:
    https_proxy: "{{http_proxy}}"
    http_proxy: "{{http_proxy}}"
  tags:
    - requirements


- name: Install memcached limits file
  template:
    src: "etc/security/limits.d/memcached_limits.conf.j2"
    dest: "/etc/security/limits.d/memcached_limits.conf"
  tags:
    - config

- name: create systemd override dir
  file:
    path: "/etc/systemd/system/memcached.service.d/"
    state: directory
  tags:
    - config
  notify:
    - reload systemd

#https://www.freedesktop.org/software/systemd/man/systemd.unit.html#id-1.11.3
#
# order will be by filenaming.
# /etc/systemd/system/memcached.service.d/noc.conf
#[Service]
#LimitNOFILE=1000
# /etc/systemd/system/memcached.service.d/override.conf
#[Service]
#LimitNOFILE=5000
#
- name: Install memcached override.conf
  template:
    src: "etc/override.conf.j2"
    dest: "/etc/systemd/system/memcached.service.d/noc.conf"
  tags:
    - config
  notify:
    - reload systemd

- name: start memcached
  service:
    name: memcached
    enabled: yes
    state: started
