# CentOS settings
---
# NOC settings
noc_system_service: noc
noc_service_pidfile: /var/run/noc.pid
# Postgres settings
postgres_system_service: postgresql
postgres_user: postgres
postgres_path: /usr/bin/postgres
postgresql_conf_path: /var/lib/pgsql/data/postgresql.conf
postgresql_hba_path: /var/lib/pgsql/data/pg_hba.conf
# Mongo settings
mongod_system_service: mongod
mongod_arbiter_system_service: mongod-arbiter
mongo_user: mongod
mongod_path: /usr/bin/mongod
mongo_path: /usr/bin/mongo
mongo_db_path: /var/lib/mongo/
mongo_log_path: /var/log/mongodb/mongod.log
mongo_arbiter_log_path: /var/log/mongodb/mongod-arbiter.log
mongo_pid: /var/run/mongodb/mongod.pid
mongo_arbiter_pid: /var/run/mongodb/mongod-arbiter.pid
mongo_fork: "true"
# Nginx settings
nginx_system_service: nginx
nginx_user: nginx
nginx_path: /usr/sbin/nginx
nginx_conf_path: /etc/nginx/conf.d/noc.conf
nginx_log_dir: /var/log/nginx
nginx_ssl_key_path: /etc/nginx/ssl/noc.key
nginx_ssl_cert_path: /etc/nginx/ssl/noc.crt
