# RHEL settings
---
mongo_fork: "true"
mongo_user: mongod
pycurl_ssl_library: nss
pgbouncer_path_pid: /var/run/pgbouncer
postgres_system_service: postgresql-{{ postgresql_version }}

memcahed_user: memcached
memcahed_conf: "/etc/sysconfig/memcached"

pgbouncer_user: pgbouncer