[package]
name = "pyip"
version = "0.1.0"
authors = ["The NOC Project"]
edition = "2018"

[lib]
name = "ip"
crate-type = ["cdylib"]

[dependencies]
byteorder = "1.4"
internet-checksum = "0.2"
pyo3 = { version = "0.14", features = ["extension-module"] }
