---
- name: Copy mongod-arbiter service file
  template:
    src: etc/systemd/system/mongod-arbiter.service.j2
    dest: /etc/systemd/system/mongod-arbiter.service
  notify:
    - restart mongod-arbiter
    - reload systemd
