- name: reload postgres
  become: yes
  service:
    name: "{{postgres_system_service}}"
    state: reloaded

- name: restart postgres
  become: yes
  service:
    name: "{{postgres_system_service}}"
    state: restarted

- name: reload telegraf
  become: yes
  service:
    name: telegraf
    state: reloaded
