---
- name: include vars file with RHEL registration
  include_vars: "vars/local.yml"

- name: Register to RHN
  redhat_subscription:
    state: present
    username: "{{rhel_subscription_username}}"
    password: "{{rhel_subscription_password}}"
    autosubscribe: true
  when: "rhel_subscription_username is defined and rhel_subscription_username !=''"
  become: true
  environment:
    http_proxy: "{{http_proxy}}"
  register: register_done

- name: Add Devel repos
  command: "/sbin/subscription-manager repos --enable rhel-7-server-optional-rpms"
  ignore_errors: yes
  become: true
  environment:
    http_proxy: "{{http_proxy}}"
  when: "register_done.changed==True"