---
dependency:
  name: galaxy

driver:
  name: delegated
  ssh_identity_file: "/tmp/temporary_ssh_key"
  ssh_identity_file_pub: "/tmp/temporary_ssh_key_pub"
  ssh_port: 22
  token: ${yc_token}
  cloud_id: ${yc_cloud_id}
  folder_id: ${yc_folder_id}
  zone: ${yc_zone}
  network_id: ${yc_network_id}
  subnet_id: ${yc_subnet_id}
  image_id: ${yc_ub16_disk}
lint:
  name: yamllint
platforms:
  - name: noc-node-ubuntu16
    distr: ubuntu16
    ssh_user: ubuntu
provisioner:
  name: ansible
  config_options:
    defaults:
      force_color: 1
  env:
    ANSIBLE_ROLES_PATH: $PWD/additional_roles:$PWD/system_roles:$PWD/noc_roles
    TOWER_SHOW_SECRETS: "True"
    ANSIBLE_STDOUT_CALLBACK: debug
    ANSIBLE_CALLBACK_WHITELIST: timer,profile_tasks
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "True"
    ANSIBLE_FORCE_COLOR: "True"
    ANSIBLE_GATHER_TIMEOUT: "60"
    ANSIBLE_TIMEOUT: "30"
    DIFF_ALWAYS: "True"
  playbooks:
    create: ../yc/create.yml
    prepare: ../yc/prepare.yml
    converge: ../yc/playbook.yml
    verify: ../common/verify.yml
    side_effect: ../common/cache.yml
    destroy: ../yc/destroy.yml
  options:
    i: inv.yml
    extra-vars: tower_dist_dir=/tmp noc_version=${NOC_BRANCH} noc_py3_ver=${PY3_VERSION}
  lint:
    name: ansible-lint
scenario:
  name: ubuntu16
  test_sequence:
    - create
    - prepare
    - converge
    - verify
    - side_effect
    - destroy
verifier:
  name: goss
  lint:
    name: yamllint
