---
- name: Add Ubuntu PostgreSQL key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  environment:
    https_proxy: "{{http_proxy}}"
    http_proxy: "{{http_proxy}}"
  tags:
    - repo

- name: Add Ubuntu PostgreSQL repo
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main"
    state: present
    update_cache: yes
  environment:
    https_proxy: "{{http_proxy}}"
    http_proxy: "{{http_proxy}}"
  tags:
    - repo

- name: "Install PostgreSQL"
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  with_items:
    - postgresql-{{ postgresql_version }}
    - postgresql-contrib-{{ postgresql_version }}
    - python-psycopg2
  environment:
    https_proxy: "{{http_proxy}}"
    http_proxy: "{{http_proxy}}"

- name: Find suitable PostgreSQL cluster
  shell: /usr/bin/pg_lsclusters -h | grep 5432 | awk '{print $1 " " $2}'
  changed_when: false
  register: pgcluster
  tags:
    - config

- name: Using PostgreSQL version
  set_fact:
    pg_cluster_version: "{{ pgcluster.stdout.split()[0].strip() }}"
    pg_cluster_name: "{{ pgcluster.stdout.split()[1].strip() }}"

- name: Set config paths
  set_fact:
    postgresql_conf_path: "/etc/postgresql/{{pg_cluster_version}}/{{pg_cluster_name}}/postgresql.conf"
    postgresql_hba_path: "/etc/postgresql/{{pg_cluster_version}}/{{pg_cluster_name}}/pg_hba.conf"
