# Debian settings
---
activator_command: "/bin/sh -c 'exec taskset -c $((%(process_num)d %% $(nproc))) ./services/activator/service.py'"
apt_cache_valid_time: 86400

mongo_arbiter_pid: " "
mongo_pid: " "
nginx_user: www-data
pgbouncer_path_pid: /var/run/postgresql

postgres_system_service: "postgresql@{{ postgres_version }}-main"
postgres_bin_dir: /usr/lib/postgresql/{{ postgres_version }}/bin
postgres_home: /var/lib/postgresql
postgres_data_dir: "{{ postgres_home }}/{{ postgres_version }}/main"
postgresql_conf_prefix: "/etc/postgresql/{{ postgres_version }}/main"
postgres_proccess: postgres

jemalloc_path: /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
