# RHEL settings
---
mongo_fork: "true"
mongo_user: mongod
pgbouncer_path_pid: /var/run/pgbouncer
postgres_system_service: postgresql-{{ postgres_version }}
postgres_bin_dir: /usr/pgsql-{{ postgres_version }}/bin
postgres_data_dir: /var/lib/pgsql/{{ postgres_version }}/data
postgresql_conf_prefix: /var/lib/pgsql/{{ postgres_version }}/data
postgresql_conf_path: "{{postgresql_conf_prefix}}/postgresql.conf"
postgresql_hba_path: "{{postgresql_conf_prefix}}/pg_hba.conf"

memcahed_user: memcached
memcahed_conf: /etc/sysconfig/memcached

pgbouncer_user: pgbouncer
zookeeper_reload_command: "systemctl reload zookeeper-server"

jemalloc_path: /lib64/libjemalloc.so.1
