---
- name: Install pre Debian 10 system packages
  apt:
    name: "{{ packages }}"
    update_cache: "True"
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  vars:
    packages:
      - python
      - python-dev
      - python-virtualenv
      - git
      - libjemalloc1
      - gcc
      - libpq-dev
      - libffi6
      - libffi-dev
      - libmemcached11
      - libmemcached-dev
      - zlib1g-dev
      - patch
      - bzip2
      - cmake
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version is version('10', '<')
  tags:
    - requirements

- name: Install Debian 10+ system packages
  apt:
    name: "{{ packages }}"
    update_cache: "True"
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  vars:
    packages:
      - python
      - python-dev
      - python3-dev
      - python3-venv
      - python-virtualenv
      - git
      - libjemalloc2
      - gcc
      - libpq-dev
      - libffi6
      - libffi-dev
      - libmemcached11
      - libmemcached-dev
      - zlib1g-dev
      - patch
      - bzip2
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version is version('10', '>=')
  tags:
    - requirements

- name: Install supervisord init script
  template:
    src: "os/Debian/etc/init.d/noc.j2"
    dest: "/etc/init.d/{{ noc_system_service }}"
    mode: "a+rx"
  when: "ansible_service_mgr != 'systemd'"

- name: Install supervisord systemd service
  template:
    src: "{{ noc_system_service }}.service.j2"
    dest: "/etc/systemd/system/{{ noc_system_service }}.service"
  when: "ansible_service_mgr == 'systemd'"
  notify: reload systemd
