# mongodb debian
---
- name: "Add MongoDB apt key"
  apt_key:
    url: "{{ item.url }}"
    id: "{{ item.id }}"
    state: present
  with_items:
    - { url: "https://www.mongodb.org/static/pgp/server-3.6.asc", id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5 }
    - { url: "https://www.mongodb.org/static/pgp/server-4.0.asc", id: 9DA31620334BD75D9DCB49F368818C72E52529D4 }
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - repo

- name: Add MongoDB repository
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/{{ mongod_version }} main"
    state: present
    update_cache: "True"
  register: mongo_repo_stat
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version != "10"
  tags:
    - repo

- name: Add MongoDB repository on Debian 10
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/{{ mongod_version }} main"
    state: present
    update_cache: "True"
  register: mongo_repo_stat
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version == "10"
  tags:
    - repo

- name: Disable Transparent Hugepages (bootloader)
  lineinfile:
    dest: /etc/default/grub
    state: present
    backrefs: "True"
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=\"\"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT=\"transparent_hugepage=never\"'
  register: dht_status

- command: update-grub
  notify: restart mongod
  when: dht_status.changed

- name: Disable Transparent Hugepages (runtime)
  shell: |
    if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
    echo never > /sys/kernel/mm/transparent_hugepage/enabled;
    echo never > /sys/kernel/mm/transparent_hugepage/defrag;
    fi
  when: dht_status.changed

- name: Set mongod defaults
  template:
    src: "os/Debian/etc/default/mongod.j2"
    dest: "/etc/default/mongod"
  notify: restart mongod
  tags:
    - config

- name: Install mongodb limits file
  template:
    src: "etc/security/limits.d/mongo_limits.conf.j2"
    dest: "/etc/security/limits.d/mongo_limits.conf"
  tags:
    - config

- name: ReInstall MongoDB on version change
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: "True"
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  when: mongo_repo_stat.changed
  vars:
    packages:
      - mongodb-org
      - mongodb-org-server
      - mongodb-org-shell
      - mongodb-org-tools
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements

- name: Install MongoDB
  apt:
    name: "mongodb-org"
    state: present
    update_cache: "True"
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements

- include_tasks: "arbiter.yml"
  when: "has_svc_mongo_arbiter | default(False)"
