---
- name: Add MongoDB apt repository key
  get_url:
    url: "{{ mongo_deb_gpgkey }}"
    dest: /etc/apt/trusted.gpg.d/mongodb.asc
    mode: '0644'
    force: true
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - repo

- name: Add MongoDB repository
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/{{ mongod_version }} multiverse"
    state: present
    update_cache: "True"
  register: mongo_repo_stat
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - repo

- name: add repo libssl1.1
  apt_repository:
    repo: "deb http://security.ubuntu.com/ubuntu focal-security main"
    state: present
    update_cache: "True"
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - repo

- name: install libssl1.1
  apt:
    name: libssl1.1
    state: present
    update_cache: "True"
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements

- name: Disable Transparent Hugepages (runtime)
  shell: |
    if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
    echo never > /sys/kernel/mm/transparent_hugepage/enabled;
    echo never > /sys/kernel/mm/transparent_hugepage/defrag;
    fi
  notify: restart mongod

- name: ReInstall MongoDB on version change
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: "True"
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  when: mongo_repo_stat.changed
  vars:
    packages:
      - mongodb-org
      - mongodb-org-server
      - mongodb-org-shell
      - mongodb-org-tools
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: "True"
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements

- name: Copy mongod service file
  template:
    src: "os/Ubuntu_22/etc/systemd/system/mongod.service.j2"
    dest: "/etc/systemd/system/mongod.service"
  register: mongod_service
  notify: restart mongod

- name: Copy systemd tmpfile
  template:
    src: etc/tmpfiles.d/mongo.conf.j2
    dest: /etc/tmpfiles.d/mongo.conf

- include_tasks: "arbiter.yml"
  when: "has_svc_mongod_arbiter | default(False)"

- name: Reload systemd daemon
  command: /bin/systemctl daemon-reload
  when: mongod_service.changed
