---
- name: Set mongod-arbiter defaults
  template: src="Debian/etc/default/mongod-arbiter.j2" dest="/etc/default/mongod-arbiter"
  notify: restart mongod-arbiter

- name: Check mongod-arbiter init file
  stat: path=/etc/init.d/mongod-arbiter
  register: s

- name: Create mongod-arbiter init file
  shell: "sed -e 's/^NAME=mongod/NAME=mongod-arbiter/' -e 's/Provides: \\+mongod/Provides:          mongod-arbiter/' < /etc/init.d/mongod > /etc/init.d/mongod-arbiter && chmod a+x /etc/init.d/mongod-arbiter"
  when: s.stat.isfile is not defined
