# mongodb debian
---
- name: "Add MongoDB apt key"
  apt_key: keyserver=keyserver.ubuntu.com id="{{ item }}"
  with_items:
    - 7F0CEB10
    - EA312927
  environment:
    https_proxy: "{{http_proxy}}"
    http_proxy: "{{http_proxy}}"
  tags:
    - repo
# there is no pakages for mongodb for jessie. so we will use whezze temporary for jessie too
- name: "Add MongoDB repository"
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/{{mongo_version}} main"
    state: present
    update_cache: yes
  environment:
    https_proxy: "{{http_proxy}}"
    http_proxy: "{{http_proxy}}"
  tags:
    - repo

- name: Disable Transparent Hugepages (bootloader)
  lineinfile: "dest=/etc/default/grub state=present backrefs=yes regexp='^GRUB_CMDLINE_LINUX_DEFAULT=\"\"' line='GRUB_CMDLINE_LINUX_DEFAULT=\"transparent_hugepage=never\"'"
  register: dht_status

- shell: update-grub
  notify: restart mongod
  when: dht_status.changed

- name: Disable Transparent Hugepages (runtime)
  shell: if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
            echo never > /sys/kernel/mm/transparent_hugepage/enabled;
            echo never > /sys/kernel/mm/transparent_hugepage/defrag;
         fi
  when: dht_status.changed

- name: Set mongod defaults
  template:
    src: "os/Debian/etc/default/mongod.j2"
    dest: "/etc/default/mongod"
  notify: restart mongod
  tags:
    - config

- name: Install mongodb limits file
  template:
    src: "etc/security/limits.d/mongo_limits.conf.j2"
    dest: "/etc/security/limits.d/mongo_limits.conf"
  tags:
    - config

- name: Install MongoDB
  apt: name="mongodb-org" state=present update_cache=yes cache_valid_time="{{apt_cache_valid_time | default (3600)}}"
  environment:
    https_proxy: "{{http_proxy}}"
    http_proxy: "{{http_proxy}}"

- include: "arbiter.yml"
  when: "{{ has_svc_mongo_arbiter | default(False) }}"
