---
- name: Add Nginx key Debian
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present
  environment:
    http_proxy: "{{http_proxy}}"
  tags:
    - repo

- name: Add Debian Nginx repo
  apt_repository:
    repo: 'deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx'
    state: present
    update_cache: yes
  environment:
    http_proxy: "{{http_proxy}}"
  tags:
    - repo

- name: Install service monitoring
  template:
    src: "{{item}}"
    dest: "/{{item[:-3]}}"
    force: no
  with_items:
    - "etc/telegraf/telegraf.d/discovery.conf.j2"
    - "etc/telegraf/telegraf.d/fm-monitor.conf.j2"
  notify: reload telegraf
  tags:
    - config

- name: Install Nginx
  apt:
    name: nginx
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
    state: latest
  environment:
    https_proxy: "{{http_proxy}}"
    http_proxy: "{{http_proxy}}"

- name: Remove default.conf site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: reload nginx
