---
forms:
  escalator:
    description: >
      <strong>Service type</strong>: Internal <br/>
      <strong>Short description</strong>: Escalator service <br/>
      <strong>Long description</strong>: Send notifications to external TT systems.<br/>
      <strong>Scale Recommendations</strong>: Have to be at least one per pool and not more than one on each node.<br/>
      <strong>docs</strong>: <a href=https://docs.getnoc.com/services-reference/escalator/ target=_blank>Escalator</a><br/>
      <strong>Placement constraint</strong>: Place more correlators to different nodes.<br/>
    power:
      default: 1
      label: "Instances"
      type: int
      max: 1
      min: 0
    loglevel:
      default: info
      label: Loglevel
      type: list
      options:
        - disabled
        - debug
        - info
        - warning
        - error
        - critical
    max_threads:
      default: 10
      label: "Escalator threads"
      type: int

services:
  escalator:
    level: global
    category: internal
    supervisord:
      command: "./services/escalator/service.py"
      process_name: "%(program_name)s"
      oom_score_adj: 5
      priority: 50
      startretries: 999
      stopwaitsecs: 3
      stdout_logfile_maxbytes: 10MB
      stdout_logfile_backups: 10
    depends:
      - noc
