---
- name: Install Ubuntu system packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  with_items:
    - less
    - telnet
    - tcpdump
    - python
    - python-dev
    - python-virtualenv
    - mercurial
    - git
    - libjemalloc1
    - gcc
    - libpq-dev
    - libffi6
    - libffi-dev
    - libmemcached11
    - libmemcached-dev
    - patch
    - bzip2
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements

- name: Install supervisord init script
  template:
    src: "noc.service.j2"
    dest: "/etc/systemd/system/{{ noc_system_service }}.service"
    mode: "a+r"
  notify: reload systemd