---
- name: Add PostgreSQL repository RHEL
  yum_repository:
    name: pgdg-{{ postgresql_version|replace(".","") }}-centos
    description: PostgreSQL {{ postgresql_version }}
    baseurl: https://download.postgresql.org/pub/repos/yum/{{ postgresql_version }}/redhat/rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}
    gpgcheck: yes
    gpgkey: https://apt.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-{{ postgresql_version|replace(".","") }}
    enabled: yes
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{http_proxy}}"
  tags:
    - repo

- name: Install CentOS system packages 1/2
  yum:
    name: "{{ item }}"
    state: present
    update_cache: no
  with_items:
   - epel-release
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements

- name: Install CentOS system packages 2/2
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
   - tcpdump
   - net-tools
   - man
   - mercurial
   - git
   - python-virtualenv
   - telnet
   - gcc
   - postgresql{{ postgresql_version|replace(".","") }}
   - postgresql-devel
   - postgresql{{ postgresql_version|replace(".","") }}-devel
   - libffi
   - libffi-devel
   - libmemcached
   - libmemcached-devel
   - zlib-devel
   - jemalloc
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements

- include: "firewall.yml"
  tags:
    - firewall

- name: Install supervisord init script
  template:
    src: "noc.service.j2"
    dest: "/etc/systemd/system/{{ noc_system_service }}.service"
    mode: "a+r"
  notify: reload systemd