- name: "Include OS-specific tasks"
  include: "os/{{ ansible_distribution }}/main.yml"

- name: Install classifier monitoring
  template:
    src: "etc/telegraf/telegraf.d/noc-classifier.conf.j2"
    dest: "{{ telegraf_confd_path }}/noc-classifier.conf"
  notify: reload telegraf
  tags:
    - config
    - telegraf


- name: Install classifier python packages
  pip:
    chdir: "{{noc_root}}"
    requirements: "requirements/classifier.txt"
    virtualenv: "{{noc_root}}"
  environment:
    https_proxy: "{{http_proxy}}"
    http_proxy: "{{http_proxy}}"
  tags:
    - requirements
