name: Build Docs
env:
  PIP_CACHE_DIR: .pip
  PYTHONPATH: src
on:
  pull_request:
    paths: &on-paths
      - ".github/workflows/build-docs.yml"
      - "mkdocs.yml"
      - "pypproject.toml"
      - "macros.py"
      - "docs/**"
      - "**.md"
  push:
    branches: [master]
    paths: *on-paths
  release:
    types: ["published"]
permissions:
  contents: write
  pull-requests: write
jobs:
  build-push:
    name: "Build & Push Docs"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Cache dependencies
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ./.pip
          key: ${{ runner.os }}-docs-${{ hashFiles('pyproject.toml') }}

      # Install dependencies
      - name: Install Dependencies
        run: pip install -IU -e .[docs]

      - name: Build Docs
        run: mkdocs build

      - name: Minify Docs
        run: python3 scripts/docs/minify.py

      - name: Build & Deploy Docs
        run: mkdocs gh-deploy --force
        if: "github.ref == 'refs/heads/master'"
